name: BLAS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenblas-dev gcc make

    - name: Build
      run: make

    - name: Run Interface Tests
      run: make test

    - name: Run Performance Tests
      run: make perf
