name: Lab12_CI

on:
  push:
    branches: [ lab_12, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev gcc make

      - name: Build
        run: make -C Lab_12/

      - name: Run Tests
        run: make -C Lab_12/ test
